// castfeat_ids.nss - GENERATED by bin/gen-legendary-feats.py.
// Do not edit. Re-run the generator instead.
//
// The caster feat proxies (roadmap ll-bonus-feat-lists). Each proxy is an
// inert feat row that the level-up page CAN offer a caster past class level
// 40, standing in for a real feat the client hides there. See
// bin/spellfeat_proxies.py for why the row exists at all.
//
// The invariant this table exists to enforce: HOLD EITHER, HOLD BOTH.
// Without it the engine offers a player the row they do not have and lets
// them waste the pick on a feat they already own.

const int CASTFEAT_COUNT = 33;

// The inert row the player actually picks.
int CastFeat_ProxyAt(int nIndex);
// The real feat it stands in for.
int CastFeat_RealAt(int nIndex);

int CastFeat_ProxyAt(int nIndex)
{
    switch (nIndex)
    {
        case 0: return 1134;  // CmbtCast_WIZ
        case 1: return 1135;  // Empower_WIZ
        case 2: return 1136;  // ExtSpell_WIZ
        case 3: return 1137;  // MaxSpell_WIZ
        case 4: return 1138;  // Quicken_WIZ
        case 5: return 1139;  // Silent_WIZ
        case 6: return 1140;  // SpellFocusAbj_WIZ
        case 7: return 1141;  // SpellPen_WIZ
        case 8: return 1142;  // StillSpell_WIZ
        case 9: return 1143;  // SpellFocusCon_WIZ
        case 10: return 1144;  // SpellFocusDiv_WIZ
        case 11: return 1145;  // SpellFocusEnc_WIZ
        case 12: return 1146;  // SpellFocusEvo_WIZ
        case 13: return 1147;  // SpellFocusIll_WIZ
        case 14: return 1148;  // SpellFocusNec_WIZ
        case 15: return 1149;  // SpellFocusTra_WIZ
        case 16: return 1150;  // EPIC_SPELL_FOCUS_ABJURATION_WIZ
        case 17: return 1151;  // EPIC_SPELL_FOCUS_CONJURATION_WIZ
        case 18: return 1152;  // EPIC_SPELL_FOCUS_DIVINATION_WIZ
        case 19: return 1153;  // EPIC_SPELL_FOCUS_ENCHANTMENT_WIZ
        case 20: return 1154;  // EPIC_SPELL_FOCUS_EVOCATION_WIZ
        case 21: return 1155;  // EPIC_SPELL_FOCUS_ILLUSION_WIZ
        case 22: return 1156;  // EPIC_SPELL_FOCUS_NECROMANCY_WIZ
        case 23: return 1157;  // EPIC_SPELL_FOCUS_TRANSMUTATION_WIZ
        case 24: return 1158;  // EPIC_AUTOMATIC_QUICKEN_1_WIZ
        case 25: return 1159;  // EPIC_AUTOMATIC_QUICKEN_2_WIZ
        case 26: return 1160;  // EPIC_AUTOMATIC_QUICKEN_3_WIZ
        case 27: return 1161;  // EPIC_AUTOMATIC_SILENT_SPELL_1_WIZ
        case 28: return 1162;  // EPIC_AUTOMATIC_SILENT_SPELL_2_WIZ
        case 29: return 1163;  // EPIC_AUTOMATIC_SILENT_SPELL_3_WIZ
        case 30: return 1164;  // EPIC_AUTOMATIC_STILL_SPELL_1_WIZ
        case 31: return 1165;  // EPIC_AUTOMATIC_STILL_SPELL_2_WIZ
        case 32: return 1166;  // EPIC_AUTOMATIC_STILL_SPELL_3_WIZ
    }
    return -1;
}

int CastFeat_RealAt(int nIndex)
{
    switch (nIndex)
    {
        case 0: return 7;  // CmbtCast
        case 1: return 11;  // Empower
        case 2: return 12;  // ExtSpell
        case 3: return 25;  // MaxSpell
        case 4: return 29;  // Quicken
        case 5: return 33;  // Silent
        case 6: return 35;  // SpellFocusAbj
        case 7: return 36;  // SpellPen
        case 8: return 37;  // StillSpell
        case 9: return 166;  // SpellFocusCon
        case 10: return 167;  // SpellFocusDiv
        case 11: return 168;  // SpellFocusEnc
        case 12: return 169;  // SpellFocusEvo
        case 13: return 170;  // SpellFocusIll
        case 14: return 171;  // SpellFocusNec
        case 15: return 172;  // SpellFocusTra
        case 16: return 610;  // FEAT_EPIC_SPELL_FOCUS_ABJURATION
        case 17: return 611;  // FEAT_EPIC_SPELL_FOCUS_CONJURATION
        case 18: return 612;  // FEAT_EPIC_SPELL_FOCUS_DIVINATION
        case 19: return 613;  // FEAT_EPIC_SPELL_FOCUS_ENCHANTMENT
        case 20: return 614;  // FEAT_EPIC_SPELL_FOCUS_EVOCATION
        case 21: return 615;  // FEAT_EPIC_SPELL_FOCUS_ILLUSION
        case 22: return 616;  // FEAT_EPIC_SPELL_FOCUS_NECROMANCY
        case 23: return 617;  // FEAT_EPIC_SPELL_FOCUS_TRANSMUTATION
        case 24: return 857;  // FEAT_EPIC_AUTOMATIC_QUICKEN_1
        case 25: return 858;  // FEAT_EPIC_AUTOMATIC_QUICKEN_2
        case 26: return 859;  // FEAT_EPIC_AUTOMATIC_QUICKEN_3
        case 27: return 860;  // FEAT_EPIC_AUTOMATIC_SILENT_SPELL_1
        case 28: return 861;  // FEAT_EPIC_AUTOMATIC_SILENT_SPELL_2
        case 29: return 862;  // FEAT_EPIC_AUTOMATIC_SILENT_SPELL_3
        case 30: return 863;  // FEAT_EPIC_AUTOMATIC_STILL_SPELL_1
        case 31: return 864;  // FEAT_EPIC_AUTOMATIC_STILL_SPELL_2
        case 32: return 865;  // FEAT_EPIC_AUTOMATIC_STILL_SPELL_3
    }
    return -1;
}
