// devcrit_map_inc.nss - GENERATED by bin/gen-devcrit-map.py. Do not edit.
//
// The base item -> Devastating Critical feat mapping that USED to live in
// baseitems.2da's EpicWeaponDevastatingCriticalFeat column. That column is
// blanked in hak_2da/baseitems.2da so the engine can never roll its
// save-or-die (roadmap devcrit-roll); this table is what is left of it, and
// it is how devcrit_atk.nss knows whose critical hit earns the bonus dice
// that replaced the instant kill.
//
// Regenerate with:  python3 bin/gen-devcrit-map.py --apply

// The feat that grants Devastating Critical with nBaseItem, or -1 for a
// base item that never had one (every non-weapon, and a few weapons).
int DevCrit_WeaponFeat(int nBaseItem);

int DevCrit_WeaponFeat(int nBaseItem)
{
    switch (nBaseItem)
    {
        case 0: return 509;
        case 1: return 512;
        case 2: return 516;
        case 3: return 528;
        case 4: return 520;
        case 5: return 521;
        case 6: return 498;
        case 7: return 499;
        case 8: return 507;
        case 9: return 500;
        case 10: return 518;
        case 11: return 508;
        case 12: return 531;
        case 13: return 513;
        case 18: return 517;
        case 22: return 496;
        case 28: return 495;
        case 31: return 497;
        case 32: return 529;
        case 33: return 530;
        case 35: return 522;
        case 36: return 506;
        case 37: return 519;
        case 38: return 514;
        case 40: return 523;
        case 41: return 527;
        case 42: return 524;
        case 47: return 501;
        case 50: return 502;
        case 51: return 510;
        case 53: return 511;
        case 55: return 526;
        case 58: return 503;
        case 59: return 525;
        case 60: return 504;
        case 61: return 505;
        case 63: return 515;
        case 69: return 532;
        case 70: return 532;
        case 71: return 532;
        case 72: return 532;
        case 78: return 506;
        case 92: return 24673;
        case 95: return 1075;
        case 108: return 955;
        case 111: return 996;
        case 210: return 24760;
        case 300: return 24764;
        case 301: return 24674;
        case 302: return 24675;
        case 303: return 24676;
        case 304: return 24677;
        case 305: return 24678;
        case 308: return 24679;
        case 309: return 496;
        case 310: return 24680;
        case 312: return 500;
        case 313: return 524;
        case 316: return 24678;
        case 317: return 24681;
        case 318: return 24682;
        case 319: return 24761;
        case 320: return 24762;
        case 321: return 24683;
        case 322: return 24684;
        case 323: return 24763;
        case 330: return 512;
    }
    return -1;
}
