// don_cheat_data.nss
// Donations Chest cheat-stock table: per slot, the union of the top-5 items
// by GP value and the top-5 items appearing in the boss-beating kits from
// module-index/counter_gear.json.
//
// AUTO-GENERATED by bin/gen-cheat-chest.py - do not hand-edit.
// The master on/off switch lives in don_cheat_inc.nss, not here.

const int DON_CHEAT_COUNT = 92;

// Resref of cheat-stock item n (0 .. DON_CHEAT_COUNT-1).
string DonCheatResRef(int n)
{
    switch (n)
    {
        // --- Head ---
        case 0:     return "item020";             // Sauron's Mask of Evil (4,515,843 gp, value)
        case 1:     return "item035";             // Dragon's Gaze (4,038,287 gp, value)
        case 2:     return "basiliskvisa002";     // Basilisk Visage (4,014,809 gp, value+boss x17)
        case 3:     return "thebalrogskull";      // The Balrog Skull (3,684,493 gp, value)
        case 4:     return "cursedoneshel002";    // Cursed Ones Helm (3,258,890 gp, value+boss x16)
        case 5:     return "heavensfaith";        // Numenors Faith (625,628 gp, boss x15)
        case 6:     return "helmofthewitchki";    // Helm of the Witch King (1,732,643 gp, boss x8)
        case 7:     return "019";                 // Urukai White Mask (116,643 gp, boss x6)
        // --- Chest ---
        case 8:     return "lesserrobe3or004";    // Arch-Robe of the Brown Wizard (9,830,723 gp, value)
        case 9:     return "cursedplate002";      // Cursed Plate (8,687,740 gp, value+boss x22)
        case 10:    return "fightersfury";        // Fighters Fury (8,539,259 gp, value)
        case 11:    return "cloth034";            // Mithral of Sauron (8,271,977 gp, value)
        case 12:    return "basiliskhard001";     // Basilisk Harded Skin (7,171,353 gp, value)
        case 13:    return "garbsoflasgalen";     // Garbs of Lasgalen (2,288,941 gp, boss x12)
        case 14:    return "meshoferynlasgal";    // Mesh of Eryn Lasgalen (4,171,873 gp, boss x7)
        case 15:    return "cloth012";            // General's Outfit (2,152,961 gp, boss x5)
        case 16:    return "096";                 // Robe of the Gwathdor Lord (1,354,241 gp, boss x4)
        // --- Boots ---
        case 17:    return "bootsofthemighty";    // Boots of the Mighty Mage (5,126,561 gp, value)
        case 18:    return "bootsofthedrider";    // Boots of the Drider Cleric (4,151,870 gp, value+boss x10)
        case 19:    return "carapaceofcha002";    // Greater Carapace of Chaos (2,249,131 gp, value)
        case 20:    return "bootsofquicke001";    // Boots of the Dol Guldur Ranger (1,776,202 gp, value)
        case 21:    return "bootsofthevalar";     // Boots of the Valar (1,117,231 gp, value+boss x10)
        case 22:    return "heavenlyboots";       // Numenorian Boots (930,251 gp, boss x20)
        case 23:    return "item133";             // Natures' Wrap (454,969 gp, boss x10)
        case 24:    return "tearhuanch2";         // Tearhuanch (100,702 gp, boss x2)
        // --- Arms ---
        case 25:    return "furyofthevala002";    // Fury of the Valar  (7,140,251 gp, value)
        case 26:    return "test";                // Dark Touch (3,969,000 gp, value)
        case 27:    return "item096";             // Chosen Fist (3,451,563 gp, value)
        case 28:    return "136";                 // Bracers of Morgrond (3,445,690 gp, value)
        case 29:    return "cursedguantle002";    // Cursed Guantlets (3,249,001 gp, value)
        case 30:    return "bracersofthedwa2";    // Bracers of the Dwarven Protector (320,411 gp, boss x25)
        case 31:    return "bracesoftheblade";    // Braces of the Bladeswinger (829,441 gp, boss x7)
        case 32:    return "etherealglove002";    // Ethereal Gloves (391,942 gp, boss x6)
        case 33:    return "010";                 // Hand of Many (932,387 gp, boss x5)
        case 34:    return "bracersofmight";      // Bracers of the Brute (182,251 gp, boss x4)
        // --- Right hand ---
        case 35:    return "avenger002";          // Avenger (20,808,100 gp, value+boss x3)
        case 36:    return "grond";               // Grond (19,577,266 gp, value)
        case 37:    return "maceofthedark001";    // Greater Mace of Morannon (18,842,266 gp, value)
        case 38:    return "doombringer";         // Doombringer (16,923,440 gp, value)
        case 39:    return "item060";             // Glamdring (16,798,876 gp, value)
        case 40:    return "mightofminas";        // Might of Minas (10,386,038 gp, boss x31)
        case 41:    return "030";                 // Sword of the Deep (8,450,030 gp, boss x12)
        case 42:    return "headsplitter005";     // Drider Slasher (10,782,562 gp, boss x7)
        case 43:    return "crossbowofthedwa";    // Crossbow of the Dwarf (2,630,036 gp, boss x3)
        // --- Left hand ---
        case 44:    return "grond";               // Grond (19,577,266 gp, value)
        case 45:    return "maceofthedark001";    // Greater Mace of Morannon (18,842,266 gp, value)
        case 46:    return "item060";             // Glamdring (16,798,876 gp, value)
        case 47:    return "handofpaladine";      // Longsword of Elrond (16,065,310 gp, value)
        case 48:    return "glamhring2";          // Flame of the West  (14,727,640 gp, value)
        case 49:    return "greatshieldofriv";    // Great Shield of Rivendell (220,869 gp, boss x3)
        case 50:    return "crossbowofthedwa";    // Crossbow of the Dwarf (2,630,036 gp, boss x2)
        case 51:    return "deadlywhisper001";    // Deadly Whisper (907,438 gp, boss x1)
        case 52:    return "shieldofthepr001";    // Shield of the Priest (275,494 gp, boss x1)
        case 53:    return "brokenbranch";        // Broken Branch (837,224 gp, boss x1)
        // --- Cloak ---
        case 54:    return "basilisktail006";     // Basilisk Tail Skin (7,567,389 gp, value+boss x3)
        case 55:    return "theshadowofgreen";    // The Shadow of Greenleaf (3,358,204 gp, value+boss x25)
        case 56:    return "item009";             // Wizard's Wrap (1,751,423 gp, value)
        case 57:    return "item054";             // Gandalf's Sorcerer Wrap (1,246,090 gp, value)
        case 58:    return "hollywoodwrap";       // Hollywood Wrap (501,761 gp, value)
        case 59:    return "cloakofmutantski";    // Cloak of Mutant Skin (484,441 gp, boss x11)
        case 60:    return "128";                 // Cloak of the Reaper (146,973 gp, boss x5)
        case 61:    return "item039";             // Gollum's Cloak (18,276 gp, boss x1)
        // --- Neck ---
        case 62:    return "undeadheart";         // Undead Heart (3,840,901 gp, value+boss x20)
        case 63:    return "131";                 // Amulet of Darkness (1,972,876 gp, value)
        case 64:    return "item090";             // The Gift of Minas (1,218,011 gp, value)
        case 65:    return "prophetsrune";        // Prophets Rune (1,190,595 gp, value)
        case 66:    return "jewelofthevalar";     // Jewel of the Valar (1,079,945 gp, boss x6)
        case 67:    return "amuletofdireprot";    // King's Amulet of Dire Protection (107,123 gp, boss x5)
        case 68:    return "amuletofhealth6";     // Amulet of Health +6 (51,841 gp, boss x2)
        // --- Belt ---
        case 69:    return "item121";             // Sauron's Chosen Belt (5,722,922 gp, value)
        case 70:    return "beltofgreatness";     // Belt of Greatness (3,419,911 gp, value)
        case 71:    return "beltofsorcerery";     // Belt of Sorcerery (2,683,241 gp, value)
        case 72:    return "valarslegacy";        // Valar's Legacy (2,040,781 gp, value)
        case 73:    return "beltofdarkwardin";    // Belt of Dark Warding (1,568,161 gp, value)
        case 74:    return "042";                 // Belt of the Orc Defender (345,031 gp, boss x6)
        case 75:    return "132";                 // Belt of Orc General (1,190,251 gp, boss x6)
        case 76:    return "wrapofthecurs002";    // Wrap of the Cursed One (1,291,876 gp, boss x6)
        case 77:    return "beltofgodlystren";    // Belt of Godly Strength (302,761 gp, boss x5)
        case 78:    return "galadhrimwiza001";    // Galadhrim Sorcers Belt (1,199,584 gp, boss x4)
        // --- Ring ---
        case 79:    return "101";                 // Lightstream Ring (3,281,602 gp, value+boss x11)
        case 80:    return "theonering";          // The One Ring (3,262,138 gp, value)
        case 81:    return "item100";             // Khamûl's Enslavement (2,158,123 gp, value)
        case 82:    return "keeperring";          // The Keeper's Ring (1,781,328 gp, value)
        case 83:    return "item1002";            // Khamûl's Enslavement (1,500,823 gp, value+boss x6)
        case 84:    return "greaterringof003";    // Greater Ring of Power (428,970 gp, boss x15)
        case 85:    return "0182";                // Ring of Speed and Magic Defenses (284,541 gp, boss x12)
        case 86:    return "ringofthedwarf";      // Ring of the Dwarf (439,453 gp, boss x5)
        // --- Ammo ---
        case 87:    return "arrowsoflegolas";     // Arrows of Legolas (8,265,807 gp, value)
        case 88:    return "divinebullets";       // Divine Bullets (2,562,383 gp, value)
        case 89:    return "divinearrows";        // Divine Arrows (1,894,922 gp, value)
        case 90:    return "divinebolts";         // Divine Bolts (1,894,922 gp, value)
        case 91:    return "thethiefcatch002";    // The Thief Catcher  (1,746,360 gp, value)
    }
    return "";
}

// Stack size for cheat-stock item n - a full quiver for ammunition, else 1.
int DonCheatStack(int n)
{
    switch (n)
    {
        case 87: // Arrows of Legolas
        case 88: // Divine Bullets
        case 89: // Divine Arrows
        case 90: // Divine Bolts
        case 91: // The Thief Catcher 
            return 99;
    }
    return 1;
}
