// jb_tracks.nss -- the jukebox's custom music track table.
//
// AUTO-GENERATED by bin/gen-music-tracks.py -- do not hand-edit.
// Add an MP3 to ~/OneDrive/Games/NWNHomersLOTR/music/mp3/ and re-run it.
//
// The row numbers below are ambientmusic.2da rows. NWScript cannot read a
// 2DA, so the table is baked out here; music/tracks.json is the source of
// truth and guarantees a row is never reassigned to another song.
//
// These are RAW ambientmusic.2da rows, and MusicBackgroundChangeDay() takes
// them as-is. (MusicBackgroundGetDayTrack() is the odd one out -- it returns
// row MINUS ONE. jb_inc.nss documents both conventions.)

int JB_GetTrackCount();
int JB_GetTrackRow(int nIndex);
string JB_GetTrackName(int nIndex);

int JB_GetTrackCount()
{
    return 5;
}

int JB_GetTrackRow(int nIndex)
{
    switch (nIndex)
    {
        case 0: return 138;   // mus_hl_drowning
        case 1: return 139;   // mus_hl_excalibur
        case 2: return 140;   // mus_hl_gonnamake
        case 3: return 141;   // mus_hl_mashur
        case 4: return 142;   // mus_hl_weliketo
    }
    return -1;
}

string JB_GetTrackName(int nIndex)
{
    switch (nIndex)
    {
        case 0: return "Drowning Pool - Bodies";
        case 1: return "Excalibur (Balloon Remix) - Nick Skitz";
        case 2: return "Gonna Make You Sweat (Everybody Dance Now)";
        case 3: return "MASHUR & KEVLAR - FINALE";
        case 4: return "We Like to Party! (The Vengabus)";
    }
    return "";
}
