// legfeat_ids_inc.nss - GENERATED by bin/gen-legendary-feats.py. Do not edit.
//
// The script-side view of the legendary feat table. Feat ids are row indices
// in hak_2da/feat.2da; the names and descriptions are the same strings that
// bin/build-lotr-tlk writes into tlk/lotr.tlk, so what a script prints and
// what the character sheet shows cannot drift apart.
//
// Re-run: python3 bin/gen-legendary-feats.py --apply

const int LEGFEAT_COUNT = 18;
const int LEGFEAT_FIRST = 1116;

// How a feat's benefit is applied. RAW writes the character's BASE
// ability score and is saved in the .bic, so it is applied exactly ONCE
// and must never be re-applied at login. EFFECT is a permanent
// supernatural effect and IS rebuilt on every login.
// HOOK grants nothing at all - the feat is an inert token that a combat
// hook elsewhere reads with GetHasFeat, so LegFeat_ApplyAll must skip it.
const int LEGFEAT_KIND_EFFECT = 0;
const int LEGFEAT_KIND_RAW    = 1;
const int LEGFEAT_KIND_HOOK   = 2;

const int FEAT_LEGENDARY_STRENGTH = 1116;
const int FEAT_LEGENDARY_DEXTERITY = 1117;
const int FEAT_LEGENDARY_CONSTITUTION = 1118;
const int FEAT_LEGENDARY_INTELLIGENCE = 1119;
const int FEAT_LEGENDARY_WISDOM = 1120;
const int FEAT_LEGENDARY_CHARISMA = 1121;
const int FEAT_LEGENDARY_PROWESS = 1122;
const int FEAT_LEGENDARY_ONSLAUGHT = 1123;
const int FEAT_LEGENDARY_BUTCHER = 1124;
const int FEAT_LEGENDARY_JUGGERNAUT = 1125;
const int FEAT_LEGENDARY_GRIP = 1126;
const int FEAT_LEGENDARY_MARKSMAN = 1127;
const int FEAT_LEGENDARY_BULWARK = 1128;
const int FEAT_LEGENDARY_RIPOSTE = 1129;
const int FEAT_LEGENDARY_REAPING = 1130;
const int FEAT_LEGENDARY_WRATH = 1131;
const int FEAT_LEGENDARY_QUARRY = 1132;
const int FEAT_LEGENDARY_SUNDERING = 1133;

// --- prerequisite helpers ------------------------------------------------
// A `prereq` expression in the generator's table is rendered verbatim into
// LegFeat_MeetsPrereq below, and THIS FILE HAS NO INCLUDES - so an
// expression may only use NWScript builtins and the helpers here.
//
// Devastating Critical is not one feat: it is one feat PER WEAPON, ids 495
// to 532 contiguous, plus 955 (dwarven waraxe) and 996 (whip) bolted on
// later by the expansions. Anything gated on 'has Devastating Critical'
// has to test the lot.
int LegFeat_HasAnyDevCrit(object oPC)
{
    int nFeat;
    for (nFeat = FEAT_EPIC_DEVASTATING_CRITICAL_CLUB;
         nFeat <= FEAT_EPIC_DEVASTATING_CRITICAL_CREATURE; nFeat++)
        if (GetHasFeat(nFeat, oPC)) return TRUE;

    return GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_DWAXE, oPC)
        || GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_WHIP, oPC);
}

// Feat id at picker index n (0 .. LEGFEAT_COUNT-1), or -1 if out of range.
int LegFeat_IdAt(int n);
// Display name / description for picker index n. Empty string if out of range.
string LegFeat_NameAt(int n);
string LegFeat_DescAt(int n);

// Ability-score feats: the ABILITY_* constant a pick boosts (-1 if the
// feat is not an ability feat) and the size of the bonus.
int LegFeat_AbilityAt(int n);
int LegFeat_BonusAt(int n);
// LEGFEAT_KIND_* - how this feat's benefit is applied.
int LegFeat_KindAt(int n);
// Short summary for the picker's effect column (e.g. "+6 Strength").
string LegFeat_EffectAt(int n);

// Prerequisites. feat.2da gates nothing - these are the whole gate, and
// they are enforced twice: the picker greys a row that fails, and
// LegFeat_Take refuses it, so a stale window cannot buy past the check.
// Ability prerequisites read BASE scores, so a +12 belt worn for the
// duration of one button press does not qualify anyone.
int    LegFeat_MeetsPrereq(object oPC, int n);
// Player-facing prerequisite text, or "" when the feat has none.
string LegFeat_PrereqAt(int n);
// The same requirement MEASURED against this character: every clause,
// each marked [ok] or [X], and each numeric one carrying the player's own
// value - "BAB 35+ (you have 34) [X], Epic Prowess [ok]". A player who
// cannot see WHICH clause failed reports the one they can see; that is
// roadmap item legendary-feat-prereq-defect-1, where a character with a
// qualifying BAB but no Epic Prowess read a greyed row as "35 is not
// accepted". Returns "" when the feat has no prerequisite.
string LegFeat_PrereqStatusAt(object oPC, int n);
// Just the FIRST unmet clause, with its measured value - short enough for
// the picker's effect column, which clips silently rather than wrapping.
// "" when the character qualifies (or the feat has no prerequisite).
string LegFeat_FirstUnmetAt(object oPC, int n);

int LegFeat_IdAt(int n)
{
    if (n < 0 || n >= LEGFEAT_COUNT) return -1;
    return LEGFEAT_FIRST + n;
}

string LegFeat_NameAt(int n)
{
    switch (n)
    {
        case 0: return "Legendary Strength";
        case 1: return "Legendary Dexterity";
        case 2: return "Legendary Constitution";
        case 3: return "Legendary Intelligence";
        case 4: return "Legendary Wisdom";
        case 5: return "Legendary Charisma";
        case 6: return "Legendary Prowess";
        case 7: return "Legendary Onslaught";
        case 8: return "Legendary Butcher";
        case 9: return "Legendary Juggernaut";
        case 10: return "Legendary Grip";
        case 11: return "Legendary Marksman";
        case 12: return "Legendary Bulwark";
        case 13: return "Legendary Riposte";
        case 14: return "Legendary Reaping";
        case 15: return "Legendary Wrath";
        case 16: return "Legendary Quarry";
        case 17: return "Legendary Sundering";
    }
    return "";
}

string LegFeat_DescAt(int n)
{
    switch (n)
    {
        case 0: return "Your might has passed out of the merely mortal. You gain a permanent +6 bonus to Strength.";
        case 1: return "You move as the wind through grass. You gain a permanent +6 bonus to Dexterity.";
        case 2: return "Hurt cannot find purchase in you. You gain a permanent +6 bonus to Constitution.";
        case 3: return "Lore long lost lies open to you. You gain a permanent +6 bonus to Intelligence.";
        case 4: return "You see the shape of things as they truly are. You gain a permanent +6 bonus to Wisdom.";
        case 5: return "Others follow where you lead, and are glad of it. You gain a permanent +6 bonus to Charisma.";
        case 6: return "Every blow you aim finds its mark. You gain a permanent +5 bonus to your attack rolls.";
        case 7: return "You strike faster than the eye can follow. You gain one additional attack each round while fighting with a melee weapon or unarmed.";
        case 8: return "You do not wound; you ruin. Whenever you score a critical hit you deal 5 extra dice of damage, scaled to your weapon: d6 for a small weapon, d8 for a medium one, d10 for a large one. This is added to the extra damage of a devastating critical, not in place of it.";
        case 9: return "Nothing moves you that you do not choose to be moved by. You are immune to knockdown, entanglement, paralysis and slow, and your weapon cannot be struck from your hand.";
        case 10: return "Two blades, one will. While you fight with a weapon in each hand you gain +4 to your attack rolls and +6 to your Armour Class.";
        case 11: return "Your shots come faster than an archer's eye can follow. You gain one additional attack each round while wielding a bow or a crossbow.";
        case 12: return "The shield is not a thing you carry; it is a thing you are. While a shield is on your arm, every blow that reaches you is reduced by 10 points, after all other reductions and resistances.";
        case 13: return "You answer the blade with the blade. Once each round, when a melee attack lands on you, you may turn it aside and strike back for your weapon's damage. You do not stop attacking to do it.";
        case 14: return "Killing feeds you. Each enemy you fell grants +2 to your attack rolls and +2 damage for 12 seconds, stacking up to five times.";
        case 15: return "Wound you and you only grow terrible. Your blows deal +1 damage for every 5% of your health that is missing, up to +20.";
        case 16: return "You finish what you have hunted. Against a favoured enemy that has fallen below half its health, you deal half again as much damage.";
        case 17: return "You do not merely strike armour; you ruin it. Your landed attacks cut 3 from your target's Armour Class, stacking three times, but never by more than the armour and shield it is actually wearing are worth.";
    }
    return "";
}

int LegFeat_AbilityAt(int n)
{
    switch (n)
    {
        case 0: return 0;
        case 1: return 1;
        case 2: return 2;
        case 3: return 3;
        case 4: return 4;
        case 5: return 5;
        case 6: return -1;
        case 7: return -1;
        case 8: return -1;
        case 9: return -1;
        case 10: return -1;
        case 11: return -1;
        case 12: return -1;
        case 13: return -1;
        case 14: return -1;
        case 15: return -1;
        case 16: return -1;
        case 17: return -1;
    }
    return -1;
}

int LegFeat_BonusAt(int n)
{
    switch (n)
    {
        case 0: return 6;
        case 1: return 6;
        case 2: return 6;
        case 3: return 6;
        case 4: return 6;
        case 5: return 6;
        case 6: return 0;
        case 7: return 0;
        case 8: return 0;
        case 9: return 0;
        case 10: return 0;
        case 11: return 0;
        case 12: return 0;
        case 13: return 0;
        case 14: return 0;
        case 15: return 0;
        case 16: return 0;
        case 17: return 0;
    }
    return 0;
}

int LegFeat_KindAt(int n)
{
    switch (n)
    {
        case 0: return LEGFEAT_KIND_RAW;
        case 1: return LEGFEAT_KIND_RAW;
        case 2: return LEGFEAT_KIND_RAW;
        case 3: return LEGFEAT_KIND_RAW;
        case 4: return LEGFEAT_KIND_RAW;
        case 5: return LEGFEAT_KIND_RAW;
        case 6: return LEGFEAT_KIND_EFFECT;
        case 7: return LEGFEAT_KIND_EFFECT;
        case 8: return LEGFEAT_KIND_HOOK;
        case 9: return LEGFEAT_KIND_EFFECT;
        case 10: return LEGFEAT_KIND_EFFECT;
        case 11: return LEGFEAT_KIND_EFFECT;
        case 12: return LEGFEAT_KIND_HOOK;
        case 13: return LEGFEAT_KIND_HOOK;
        case 14: return LEGFEAT_KIND_HOOK;
        case 15: return LEGFEAT_KIND_HOOK;
        case 16: return LEGFEAT_KIND_HOOK;
        case 17: return LEGFEAT_KIND_HOOK;
    }
    return LEGFEAT_KIND_EFFECT;
}

string LegFeat_EffectAt(int n)
{
    switch (n)
    {
        case 0: return "+6 Strength (base)";
        case 1: return "+6 Dexterity (base)";
        case 2: return "+6 Constitution (base)";
        case 3: return "+6 Intelligence (base)";
        case 4: return "+6 Wisdom (base)";
        case 5: return "+6 Charisma (base)";
        case 6: return "+5 attack bonus";
        case 7: return "+1 melee attack per round";
        case 8: return "+5 damage dice on a critical";
        case 9: return "immune to knockdown, entangle, paralysis, slow and disarm";
        case 10: return "+4 attack, +6 AC while dual-wielding";
        case 11: return "+1 ranged attack per round (bow/crossbow)";
        case 12: return "-10 damage taken while a shield is equipped";
        case 13: return "1/round counter-attack when hit in melee";
        case 14: return "+2 attack/+2 damage per kill, 12s, stacks 5";
        case 15: return "+1 damage per 5% health missing, max +20";
        case 16: return "+50% damage to favoured enemies below 50% HP";
        case 17: return "-3 target AC per hit, stacks 3, capped at its armour+shield AC";
    }
    return "";
}

// --- clause renderers ----------------------------------------------------
// The three functions below turn ONE clause into text. They exist so that
// what the picker shows and what the picker tests come out of the same
// declaration in the generator - the two used to be independent hand-typed
// strings, which is how a player with a qualifying BAB and no Epic Prowess
// came to report that "35 is not accepted" (legendary-feat-prereq-defect-1).

// The ask, unmeasured: "BAB 35+", "Discipline 30+ ranks".
string LegFeat_ReqAsk(string sLabel, int nMin, string sUnit)
{
    string s = sLabel + " " + IntToString(nMin) + "+";
    if (sUnit != "") s += " " + sUnit;
    return s;
}

// The ask with this character's own value: "BAB 35+ (you have 34)".
string LegFeat_ReqHave(string sLabel, int nMin, string sUnit, int nHave)
{
    return LegFeat_ReqAsk(sLabel, nMin, sUnit)
         + " (you have " + IntToString(nHave) + ")";
}

// Pass/fail marker. ASCII on purpose - a non-ASCII byte in a .nss is a
// recorded trap in this repo, and this string reaches the NUI and the chat
// log both.
string LegFeat_ReqMark(string sBody, int bMet)
{
    return sBody + (bMet ? " [ok]" : " [X]");
}

// A numeric clause, fully rendered. nHave is passed in so the generator can
// evaluate the getter exactly once at the call site.
string LegFeat_ReqNum(string sLabel, int nMin, string sUnit, int nHave)
{
    return LegFeat_ReqMark(LegFeat_ReqHave(sLabel, nMin, sUnit, nHave),
                           nHave >= nMin);
}

// Each case ANDs the feat's clauses from the generator's table. A numeric
// clause is always emitted as `(expr) >= minimum` - the generator cannot
// express `>`, which is what makes "treated as >=, not >" a property of the
// build rather than a habit. A feat with no prerequisite emits no case and
// falls through to TRUE.
int LegFeat_MeetsPrereq(object oPC, int n)
{
    switch (n)
    {
        case 6: return ((GetBaseAttackBonus(oPC)) >= 35 && GetHasFeat(FEAT_EPIC_PROWESS, oPC));
        case 7: return ((GetBaseAttackBonus(oPC)) >= 30 && (GetLevelByClass(CLASS_TYPE_MONK, oPC)) >= 30);
        case 8: return (LegFeat_HasAnyDevCrit(oPC));
        case 9: return ((GetBaseAttackBonus(oPC)) >= 20 && (GetSkillRank(SKILL_DISCIPLINE, oPC, TRUE)) >= 30);
        case 10: return (GetHasFeat(FEAT_AMBIDEXTERITY, oPC) && GetHasFeat(FEAT_IMPROVED_TWO_WEAPON_FIGHTING, oPC) && GetHasFeat(FEAT_WEAPON_FINESSE, oPC));
        case 11: return (GetHasFeat(FEAT_RAPID_SHOT, oPC) && GetHasFeat(FEAT_POINT_BLANK_SHOT, oPC) && (GetBaseAttackBonus(oPC)) >= 30);
        case 12: return (GetHasFeat(FEAT_SHIELD_PROFICIENCY, oPC) && (GetBaseAttackBonus(oPC)) >= 15);
        case 13: return ((GetSkillRank(SKILL_PARRY, oPC, TRUE)) >= 60);
        case 14: return (GetHasFeat(FEAT_GREAT_CLEAVE, oPC) && (GetBaseAttackBonus(oPC)) >= 35);
        case 15: return ((GetAbilityScore(oPC, ABILITY_CONSTITUTION, TRUE)) >= 21);
        case 16: return ((GetLevelByClass(CLASS_TYPE_RANGER, oPC)) >= 30);
        case 17: return ((GetBaseAttackBonus(oPC)) >= 35 && GetHasFeat(FEAT_CALLED_SHOT, oPC));
    }
    return TRUE;
}

string LegFeat_PrereqAt(int n)
{
    switch (n)
    {
        case 6: return "BAB 35+, Epic Prowess";
        case 7: return "BAB 30+, Monk level 30+";
        case 8: return "Devastating Critical (any weapon)";
        case 9: return "BAB 20+, Discipline 30+ ranks";
        case 10: return "Ambidexterity, Improved Two-Weapon Fighting, Weapon Finesse";
        case 11: return "Rapid Shot, Point Blank Shot, BAB 30+";
        case 12: return "Shield Proficiency, BAB 15+";
        case 13: return "Parry 60+ ranks";
        case 14: return "Great Cleave, BAB 35+";
        case 15: return "Constitution 21+ (base)";
        case 16: return "Ranger level 30+";
        case 17: return "BAB 35+, Called Shot";
    }
    return "";
}

string LegFeat_PrereqStatusAt(object oPC, int n)
{
    switch (n)
    {
        case 6: return LegFeat_ReqNum("BAB", 35, "", GetBaseAttackBonus(oPC))
                 + ", " + LegFeat_ReqMark("Epic Prowess", GetHasFeat(FEAT_EPIC_PROWESS, oPC));
        case 7: return LegFeat_ReqNum("BAB", 30, "", GetBaseAttackBonus(oPC))
                 + ", " + LegFeat_ReqNum("Monk level", 30, "", GetLevelByClass(CLASS_TYPE_MONK, oPC));
        case 8: return LegFeat_ReqMark("Devastating Critical (any weapon)", LegFeat_HasAnyDevCrit(oPC));
        case 9: return LegFeat_ReqNum("BAB", 20, "", GetBaseAttackBonus(oPC))
                 + ", " + LegFeat_ReqNum("Discipline", 30, "ranks", GetSkillRank(SKILL_DISCIPLINE, oPC, TRUE));
        case 10: return LegFeat_ReqMark("Ambidexterity", GetHasFeat(FEAT_AMBIDEXTERITY, oPC))
                 + ", " + LegFeat_ReqMark("Improved Two-Weapon Fighting", GetHasFeat(FEAT_IMPROVED_TWO_WEAPON_FIGHTING, oPC))
                 + ", " + LegFeat_ReqMark("Weapon Finesse", GetHasFeat(FEAT_WEAPON_FINESSE, oPC));
        case 11: return LegFeat_ReqMark("Rapid Shot", GetHasFeat(FEAT_RAPID_SHOT, oPC))
                 + ", " + LegFeat_ReqMark("Point Blank Shot", GetHasFeat(FEAT_POINT_BLANK_SHOT, oPC))
                 + ", " + LegFeat_ReqNum("BAB", 30, "", GetBaseAttackBonus(oPC));
        case 12: return LegFeat_ReqMark("Shield Proficiency", GetHasFeat(FEAT_SHIELD_PROFICIENCY, oPC))
                 + ", " + LegFeat_ReqNum("BAB", 15, "", GetBaseAttackBonus(oPC));
        case 13: return LegFeat_ReqNum("Parry", 60, "ranks", GetSkillRank(SKILL_PARRY, oPC, TRUE));
        case 14: return LegFeat_ReqMark("Great Cleave", GetHasFeat(FEAT_GREAT_CLEAVE, oPC))
                 + ", " + LegFeat_ReqNum("BAB", 35, "", GetBaseAttackBonus(oPC));
        case 15: return LegFeat_ReqNum("Constitution", 21, "(base)", GetAbilityScore(oPC, ABILITY_CONSTITUTION, TRUE));
        case 16: return LegFeat_ReqNum("Ranger level", 30, "", GetLevelByClass(CLASS_TYPE_RANGER, oPC));
        case 17: return LegFeat_ReqNum("BAB", 35, "", GetBaseAttackBonus(oPC))
                 + ", " + LegFeat_ReqMark("Called Shot", GetHasFeat(FEAT_CALLED_SHOT, oPC));
    }
    return "";
}

string LegFeat_FirstUnmetAt(object oPC, int n)
{
    switch (n)
    {
        case 6:
            if (!((GetBaseAttackBonus(oPC)) >= 35))
                return LegFeat_ReqHave("BAB", 35, "", GetBaseAttackBonus(oPC));
            if (!(GetHasFeat(FEAT_EPIC_PROWESS, oPC)))
                return "Epic Prowess";
            break;
        case 7:
            if (!((GetBaseAttackBonus(oPC)) >= 30))
                return LegFeat_ReqHave("BAB", 30, "", GetBaseAttackBonus(oPC));
            if (!((GetLevelByClass(CLASS_TYPE_MONK, oPC)) >= 30))
                return LegFeat_ReqHave("Monk level", 30, "", GetLevelByClass(CLASS_TYPE_MONK, oPC));
            break;
        case 8:
            if (!(LegFeat_HasAnyDevCrit(oPC)))
                return "Devastating Critical (any weapon)";
            break;
        case 9:
            if (!((GetBaseAttackBonus(oPC)) >= 20))
                return LegFeat_ReqHave("BAB", 20, "", GetBaseAttackBonus(oPC));
            if (!((GetSkillRank(SKILL_DISCIPLINE, oPC, TRUE)) >= 30))
                return LegFeat_ReqHave("Discipline", 30, "ranks", GetSkillRank(SKILL_DISCIPLINE, oPC, TRUE));
            break;
        case 10:
            if (!(GetHasFeat(FEAT_AMBIDEXTERITY, oPC)))
                return "Ambidexterity";
            if (!(GetHasFeat(FEAT_IMPROVED_TWO_WEAPON_FIGHTING, oPC)))
                return "Improved Two-Weapon Fighting";
            if (!(GetHasFeat(FEAT_WEAPON_FINESSE, oPC)))
                return "Weapon Finesse";
            break;
        case 11:
            if (!(GetHasFeat(FEAT_RAPID_SHOT, oPC)))
                return "Rapid Shot";
            if (!(GetHasFeat(FEAT_POINT_BLANK_SHOT, oPC)))
                return "Point Blank Shot";
            if (!((GetBaseAttackBonus(oPC)) >= 30))
                return LegFeat_ReqHave("BAB", 30, "", GetBaseAttackBonus(oPC));
            break;
        case 12:
            if (!(GetHasFeat(FEAT_SHIELD_PROFICIENCY, oPC)))
                return "Shield Proficiency";
            if (!((GetBaseAttackBonus(oPC)) >= 15))
                return LegFeat_ReqHave("BAB", 15, "", GetBaseAttackBonus(oPC));
            break;
        case 13:
            if (!((GetSkillRank(SKILL_PARRY, oPC, TRUE)) >= 60))
                return LegFeat_ReqHave("Parry", 60, "ranks", GetSkillRank(SKILL_PARRY, oPC, TRUE));
            break;
        case 14:
            if (!(GetHasFeat(FEAT_GREAT_CLEAVE, oPC)))
                return "Great Cleave";
            if (!((GetBaseAttackBonus(oPC)) >= 35))
                return LegFeat_ReqHave("BAB", 35, "", GetBaseAttackBonus(oPC));
            break;
        case 15:
            if (!((GetAbilityScore(oPC, ABILITY_CONSTITUTION, TRUE)) >= 21))
                return LegFeat_ReqHave("Constitution", 21, "(base)", GetAbilityScore(oPC, ABILITY_CONSTITUTION, TRUE));
            break;
        case 16:
            if (!((GetLevelByClass(CLASS_TYPE_RANGER, oPC)) >= 30))
                return LegFeat_ReqHave("Ranger level", 30, "", GetLevelByClass(CLASS_TYPE_RANGER, oPC));
            break;
        case 17:
            if (!((GetBaseAttackBonus(oPC)) >= 35))
                return LegFeat_ReqHave("BAB", 35, "", GetBaseAttackBonus(oPC));
            if (!(GetHasFeat(FEAT_CALLED_SHOT, oPC)))
                return "Called Shot";
            break;
    }
    return "";
}
