// legfeat_ids_inc.nss — GENERATED by bin/gen-legendary-feats.py. Do not edit.
//
// The script-side view of the legendary feat table. Feat ids are row indices
// in hak_2da/feat.2da; the names and descriptions are the same strings that
// bin/build-lotr-tlk writes into tlk/lotr.tlk, so what a script prints and
// what the character sheet shows cannot drift apart.
//
// Re-run: python3 bin/gen-legendary-feats.py --apply

const int LEGFEAT_COUNT = 9;
const int LEGFEAT_FIRST = 1116;

// How a feat's benefit is applied. RAW writes the character's BASE
// ability score and is saved in the .bic, so it is applied exactly ONCE
// and must never be re-applied at login. EFFECT is a permanent
// supernatural effect and IS rebuilt on every login.
// HOOK grants nothing at all — the feat is an inert token that a combat
// hook elsewhere reads with GetHasFeat, so LegFeat_ApplyAll must skip it.
const int LEGFEAT_KIND_EFFECT = 0;
const int LEGFEAT_KIND_RAW    = 1;
const int LEGFEAT_KIND_HOOK   = 2;

const int FEAT_LEGENDARY_STRENGTH = 1116;
const int FEAT_LEGENDARY_DEXTERITY = 1117;
const int FEAT_LEGENDARY_CONSTITUTION = 1118;
const int FEAT_LEGENDARY_INTELLIGENCE = 1119;
const int FEAT_LEGENDARY_WISDOM = 1120;
const int FEAT_LEGENDARY_CHARISMA = 1121;
const int FEAT_LEGENDARY_PROWESS = 1122;
const int FEAT_LEGENDARY_ONSLAUGHT = 1123;
const int FEAT_LEGENDARY_BUTCHER = 1124;

// --- prerequisite helpers ------------------------------------------------
// A `prereq` expression in the generator's table is rendered verbatim into
// LegFeat_MeetsPrereq below, and THIS FILE HAS NO INCLUDES — so an
// expression may only use NWScript builtins and the helpers here.
//
// Devastating Critical is not one feat: it is one feat PER WEAPON, ids 495
// to 532 contiguous, plus 955 (dwarven waraxe) and 996 (whip) bolted on
// later by the expansions. Anything gated on 'has Devastating Critical'
// has to test the lot.
int LegFeat_HasAnyDevCrit(object oPC)
{
    int nFeat;
    for (nFeat = FEAT_EPIC_DEVASTATING_CRITICAL_CLUB;
         nFeat <= FEAT_EPIC_DEVASTATING_CRITICAL_CREATURE; nFeat++)
        if (GetHasFeat(nFeat, oPC)) return TRUE;

    return GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_DWAXE, oPC)
        || GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_WHIP, oPC);
}

// Feat id at picker index n (0 .. LEGFEAT_COUNT-1), or -1 if out of range.
int LegFeat_IdAt(int n);
// Display name / description for picker index n. Empty string if out of range.
string LegFeat_NameAt(int n);
string LegFeat_DescAt(int n);

// Ability-score feats: the ABILITY_* constant a pick boosts (-1 if the
// feat is not an ability feat) and the size of the bonus.
int LegFeat_AbilityAt(int n);
int LegFeat_BonusAt(int n);
// LEGFEAT_KIND_* — how this feat's benefit is applied.
int LegFeat_KindAt(int n);
// Short summary for the picker's effect column (e.g. "+6 Strength").
string LegFeat_EffectAt(int n);

// Prerequisites. feat.2da gates nothing — these are the whole gate, and
// they are enforced twice: the picker greys a row that fails, and
// LegFeat_Take refuses it, so a stale window cannot buy past the check.
// Ability prerequisites read BASE scores, so a +12 belt worn for the
// duration of one button press does not qualify anyone.
int    LegFeat_MeetsPrereq(object oPC, int n);
// Player-facing prerequisite text, or "" when the feat has none.
string LegFeat_PrereqAt(int n);

int LegFeat_IdAt(int n)
{
    if (n < 0 || n >= LEGFEAT_COUNT) return -1;
    return LEGFEAT_FIRST + n;
}

string LegFeat_NameAt(int n)
{
    switch (n)
    {
        case 0: return "Legendary Strength";
        case 1: return "Legendary Dexterity";
        case 2: return "Legendary Constitution";
        case 3: return "Legendary Intelligence";
        case 4: return "Legendary Wisdom";
        case 5: return "Legendary Charisma";
        case 6: return "Legendary Prowess";
        case 7: return "Legendary Onslaught";
        case 8: return "Legendary Butcher";
    }
    return "";
}

string LegFeat_DescAt(int n)
{
    switch (n)
    {
        case 0: return "Your might has passed out of the merely mortal. You gain a permanent +6 bonus to Strength.";
        case 1: return "You move as the wind through grass. You gain a permanent +6 bonus to Dexterity.";
        case 2: return "Hurt cannot find purchase in you. You gain a permanent +6 bonus to Constitution.";
        case 3: return "Lore long lost lies open to you. You gain a permanent +6 bonus to Intelligence.";
        case 4: return "You see the shape of things as they truly are. You gain a permanent +6 bonus to Wisdom.";
        case 5: return "Others follow where you lead, and are glad of it. You gain a permanent +6 bonus to Charisma.";
        case 6: return "Every blow you aim finds its mark. You gain a permanent +5 bonus to your attack rolls.";
        case 7: return "You strike faster than the eye can follow. You gain one additional attack each round while fighting with a melee weapon or unarmed.";
        case 8: return "You do not wound; you ruin. Whenever you score a critical hit you deal 5 extra dice of damage, scaled to your weapon: d6 for a small weapon, d8 for a medium one, d10 for a large one. This is added to the extra damage of a devastating critical, not in place of it.";
    }
    return "";
}

int LegFeat_AbilityAt(int n)
{
    switch (n)
    {
        case 0: return 0;
        case 1: return 1;
        case 2: return 2;
        case 3: return 3;
        case 4: return 4;
        case 5: return 5;
        case 6: return -1;
        case 7: return -1;
        case 8: return -1;
    }
    return -1;
}

int LegFeat_BonusAt(int n)
{
    switch (n)
    {
        case 0: return 6;
        case 1: return 6;
        case 2: return 6;
        case 3: return 6;
        case 4: return 6;
        case 5: return 6;
        case 6: return 0;
        case 7: return 0;
        case 8: return 0;
    }
    return 0;
}

int LegFeat_KindAt(int n)
{
    switch (n)
    {
        case 0: return LEGFEAT_KIND_RAW;
        case 1: return LEGFEAT_KIND_RAW;
        case 2: return LEGFEAT_KIND_RAW;
        case 3: return LEGFEAT_KIND_RAW;
        case 4: return LEGFEAT_KIND_RAW;
        case 5: return LEGFEAT_KIND_RAW;
        case 6: return LEGFEAT_KIND_EFFECT;
        case 7: return LEGFEAT_KIND_EFFECT;
        case 8: return LEGFEAT_KIND_HOOK;
    }
    return LEGFEAT_KIND_EFFECT;
}

string LegFeat_EffectAt(int n)
{
    switch (n)
    {
        case 0: return "+6 Strength (base)";
        case 1: return "+6 Dexterity (base)";
        case 2: return "+6 Constitution (base)";
        case 3: return "+6 Intelligence (base)";
        case 4: return "+6 Wisdom (base)";
        case 5: return "+6 Charisma (base)";
        case 6: return "+5 attack bonus";
        case 7: return "+1 melee attack per round";
        case 8: return "+5 damage dice on a critical";
    }
    return "";
}

// Each case is the feat's `prereq` expression from the generator's table,
// rendered verbatim. A feat with no prerequisite emits no case and falls
// through to TRUE.
int LegFeat_MeetsPrereq(object oPC, int n)
{
    switch (n)
    {
        case 6: return (GetBaseAttackBonus(oPC) >= 35 && GetHasFeat(FEAT_EPIC_PROWESS, oPC));
        case 7: return (GetBaseAttackBonus(oPC) >= 30 && GetLevelByClass(CLASS_TYPE_MONK, oPC) >= 30);
        case 8: return (LegFeat_HasAnyDevCrit(oPC));
    }
    return TRUE;
}

string LegFeat_PrereqAt(int n)
{
    switch (n)
    {
        case 6: return "BAB 35+, Epic Prowess";
        case 7: return "BAB 30+, Monk level 30+";
        case 8: return "Devastating Critical (any weapon)";
    }
    return "";
}
