// AUTO-GENERATED by nwn-manager repack — regenerated each build, do not edit.
// Opt in from any module event: ExecuteScript("nwnmgr_bstamp", oPC);
void main() { SendMessageToPC(OBJECT_SELF, "Module last edited: 2026-07-11 13:40 CDT (git LOTRv01-365-gcbd5c5f8fc9-dirty)"); }
