// AUTO-GENERATED by nwn-manager repack — regenerated each build, do not edit.
// Opt in from any module event: ExecuteScript("nwnmgr_bstamp", oPC);
void main() { SendMessageToPC(OBJECT_SELF, "Module last edited: 2026-06-29 06:34 CDT (git LOTRv01-107-geeeb5bfa57c-dirty)"); }
