// AUTO-GENERATED by nwn-manager repack — regenerated each build, do not edit.
// Opt in from any module event: ExecuteScript("nwnmgr_bstamp", oPC);
void main() { SendMessageToPC(OBJECT_SELF, "Module last edited: 2026-07-07 15:37 CDT (git LOTRv01-302-g18da63e8cab)"); }
