// GENERATED by bin/season-profile.py from SEASON_ROLE in server.env.
// DO NOT EDIT - `season-profile.py --check` is a repack build gate, so a
// hand edit here fails the next build rather than shipping.
//
// This environment's role: dev
//
// Flip behaviour by editing SEASON_ROLE in server.env and re-running
//     python3 bin/season-profile.py --apply
// The role/flag matrix lives in that script, not here.

const int SP_DEV_TOOLS   = TRUE;
const int SP_CHEAT_CHEST = TRUE;
const int SP_WIPE_NOTICE = FALSE;
