#!/usr/bin/env python3
"""Respawn-override divergence check (build-time smoke test).

The module respawns dead static creatures from their *blueprint*
(`unpacked/se_respawn_inc.nss` → `CreateObject(GetResRef(self), …)`), preserving
only the tag. So any placement whose identity differs from what its blueprint
would re-create silently reverts after the first death — name, faction,
abilities, classes, feats, special abilities, equipment (resref *and* slot),
carried inventory, natural AC, race, or conversation. (The bug that produced Carn
Dum City's "Numanan Numerocks Second Hand" respawning as the blueprint's "Numarok
The Black Hand".)

LOOT (the `Dropable` flag) is checked too, but on its own terms: a placement
that disagrees with its blueprint about whether an item drops gives loot that
works exactly once per reboot -- as placed until that creature first dies, as
the blueprint says forever after. Which side is right is a judgement call
(intended loot the blueprint forgot, vs. a hand-edited placement), so the cases
that predate this check are grandfathered in tests/known_loot_divergence.json
and merely REPORTED. Anything not in that file fails the build. The decision
document is CLAUDE-loot-divergence-audit.md, generated by
bin/audit-loot-divergence.py; the gate also names baseline entries that no
longer diverge, so the file cannot rot silently.

Deliberately NOT part of identity: PortraitId, SoundSetFile, Gender,
ChallengeRating, Appearance_Type, Appearance_Head and the colour/body-part fields.
They revert on respawn too, and ~57 placements across ~26 blueprints diverge on
them today — closing that is its own piece of work, not a silent build break.

`bin/split-divergent-creatures.py` fixed every existing case by giving each
diverging placement its own blueprint. This gate keeps it that way:

    LOCAL base (a <base>.utc.json exists):
        every static placement's identity must equal the blueprint's identity.
    STOCK base (no local .utc — a CEP/base-game blueprint):
        all of its static placements must share one identity (we can't read the
        stock baseline, but divergence between placements is provable).

"Identity" mirrors `bin/split-divergent-creatures.py` / nwn-wiki `_creature_key`
plus name, faction and conversation. The helpers below are duplicated from that
script intentionally, matching the standalone style of check_spawn_leash.py.

Scans unpacked/ directly (module-index/ is gitignored and may be absent on a
fresh clone). Exits 0 if all placements are respawn-safe, 1 otherwise.
"""

import glob
import json
import os
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UNPACKED = os.path.join(ROOT, "unpacked")


def fld(struct, key):
    v = struct.get(key) if isinstance(struct, dict) else None
    return v.get("value") if isinstance(v, dict) else None


def loc(v):
    if isinstance(v, dict):
        val = v.get("value")
        if isinstance(val, dict):
            return val.get("0")
    return None


def list_items(struct, key):
    v = struct.get(key)
    if isinstance(v, dict):
        v = v.get("value")
    return v if isinstance(v, list) else []


def combat_key(s):
    abilities = tuple(fld(s, a) for a in ("Str", "Dex", "Con", "Int", "Wis", "Cha"))
    classes = tuple(sorted(
        (fld(cl, "Class"), fld(cl, "ClassLevel")) for cl in list_items(s, "ClassList")))
    feats = tuple(sorted(
        int(fld(f, "Feat")) for f in list_items(s, "FeatList") if fld(f, "Feat") is not None))
    spec = tuple(sorted(
        (fld(x, "Spell"), fld(x, "SpellCasterLevel")) for x in list_items(s, "SpecAbilityList")))
    # `__struct_id` is a bare int, not a {"type":..,"value":..} wrapper, so it must be
    # read directly -- fld() only unwraps dicts and would return None for every slot,
    # silently reducing this to a multiset of resrefs (a weapon in the wrong hand, or
    # armour filed as a creature item, used to pass).
    equip = tuple(sorted(
        (e.get("__struct_id"), (fld(e, "EquippedRes") or fld(e, "TemplateResRef") or ""))
        for e in list_items(s, "Equip_ItemList")))
    # Carried inventory is what the creature drops, so blueprint/instance drift here
    # changes loot from the first respawn onward.
    inventory = tuple(sorted(
        (fld(e, "InventoryRes") or fld(e, "TemplateResRef") or "")
        for e in list_items(s, "ItemList")))
    # Droppability, tracked separately from the resref lists above so a mismatch
    # can be REPORTED against tests/known_loot_divergence.json rather than
    # failing outright (see loot_key / KNOWN_LOOT below). The flag decides
    # whether players get the item at all, and a placement that disagrees with
    # its blueprint gives loot that works exactly once per reboot -- as placed
    # until the creature first dies, as the blueprint says forever after.
    return (abilities, classes, feats, spec, equip, inventory,
            fld(s, "NaturalAC"), fld(s, "Race"))


def loot_key(s):
    """(list, item resref) -> sorted tuple of Dropable flags.

    A tuple rather than one value because a creature can carry several copies of
    an item with different flags -- comparing multisets keeps that honest
    instead of letting the last copy win. An absent flag is 0, which is both the
    toolset default and how the engine reads it.
    """
    out = defaultdict(list)
    for key, where in (("Equip_ItemList", "equipped"), ("ItemList", "inventory")):
        for e in list_items(s, key):
            resref = (fld(e, "EquippedRes") or fld(e, "InventoryRes")
                      or fld(e, "TemplateResRef") or "")
            if resref:
                out[(where, resref)].append(int(fld(e, "Dropable") or 0))
    return {k: tuple(sorted(v)) for k, v in out.items()}


def load_known_loot():
    """The grandfathered loot divergences, reported but not gated.

    Every case in it predates this check. Anything NOT in it fails the build.
    Regenerate with `bin/audit-loot-divergence.py --baseline <file>`; the
    decision document is CLAUDE-loot-divergence-audit.md.
    """
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "known_loot_divergence.json")
    try:
        with open(path, encoding="utf-8") as fh:
            return set(json.load(fh).get("known", []))
    except (OSError, json.JSONDecodeError):
        # A missing or corrupt baseline must not silently disable the check --
        # an empty known-list makes every existing divergence fail loudly.
        print(f"[divergent-creatures] WARNING: cannot read {path}; "
              "treating every loot divergence as new", file=sys.stderr)
        return set()


def display_name(s):
    return ((loc(s.get("FirstName")) or "") + " " + (loc(s.get("LastName")) or "")).strip()


def identity_key(s):
    return (display_name(s).lower(), fld(s, "FactionID"),
            (fld(s, "Conversation") or "").lower(), combat_key(s))


def local_blueprint(resref, cache):
    if resref not in cache:
        p = os.path.join(UNPACKED, f"{resref}.utc.json")
        cache[resref] = json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None
    return cache[resref]


def main():
    cache = {}
    known_loot = load_known_loot()
    # base -> list of (area, idx, identity, display_name)
    placements = defaultdict(list)
    # base -> list of (area, idx, loot map) -- tracked separately from identity
    # because loot divergence is reported against the known-list, not gated.
    loot_placements = defaultdict(list)
    for gf in sorted(glob.glob(os.path.join(UNPACKED, "*.git.json"))):
        area = os.path.basename(gf)[:-len(".git.json")]
        try:
            d = json.load(open(gf, encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as e:
            print(f"[divergent-creatures] FAIL: unreadable {area}.git.json: {e}", file=sys.stderr)
            return 1
        cl = d.get("Creature List")
        if not cl:
            continue
        for idx, c in enumerate(cl["value"]):
            base = fld(c, "TemplateResRef")
            if base:
                placements[base].append((area, idx, identity_key(c), display_name(c) or "(unnamed)"))
                loot_placements[base].append((area, idx, loot_key(c)))

    failures = []  # (base, kind, detail)
    for base, plist in sorted(placements.items()):
        bp = local_blueprint(base, cache)
        if bp is not None:
            base_ident = identity_key(bp)
            bad = [(a, i, nm) for a, i, ident, nm in plist if ident != base_ident]
            if bad:
                names = sorted({nm for _a, _i, nm in bad})
                where = ", ".join(f"{a}#{i}" for a, i, _nm in bad[:4])
                failures.append((base, "local",
                                 f'{len(bad)} placement(s) differ from blueprint '
                                 f'"{display_name(bp) or base}": {names} @ {where}'))
        else:
            idents = {ident for _a, _i, ident, _nm in plist}
            if len(idents) > 1:
                names = sorted({nm for _a, _i, _id, nm in plist})
                failures.append((base, "stock",
                                 f'stock blueprint placed under {len(idents)} identities: {names}'))

    # Loot (droppability). Only local blueprints can be checked -- a stock
    # blueprint has no readable baseline. New cases fail; grandfathered ones are
    # reported so the build stays green while they are worked through.
    # Known cases are collapsed to one line per distinct blueprint/area/item --
    # the granularity the decision is taken at, and the difference between a
    # 26-line wall on every build and a readable footnote.
    loot_new, loot_known, seen_keys = [], {}, set()
    for base, plist in sorted(loot_placements.items()):
        bp = local_blueprint(base, cache)
        if bp is None:
            continue
        bp_loot = loot_key(bp)
        for area, idx, inst_loot in plist:
            for key, inst_flags in sorted(inst_loot.items()):
                bp_flags = bp_loot.get(key)
                # Item missing from one side entirely is an EQUIPMENT/INVENTORY
                # divergence, already gated above -- don't double-report it.
                if bp_flags is None or bp_flags == inst_flags:
                    continue
                where, item = key
                ident = "|".join((base, area, where, item))
                seen_keys.add(ident)
                if ident in known_loot:
                    seen = loot_known.setdefault(
                        ident, {"base": base, "area": area, "where": where,
                                "item": item, "bp": bp_flags,
                                "inst": inst_flags, "count": 0})
                    seen["count"] += 1
                else:
                    loot_new.append(
                        f"{base:<20} {area}#{idx} {where} {item}: "
                        f"blueprint={bp_flags} instance={inst_flags}")

    for case in loot_known.values():
        placements_note = ("" if case["count"] == 1
                           else f" x{case['count']} placements")
        print(f"[divergent-creatures] KNOWN loot divergence (reported, not gated) — "
              f"{case['base']} in {case['area']}{placements_note}: "
              f"{case['where']} {case['item']} "
              f"blueprint={case['bp']} instance={case['inst']}")

    stale = sorted(known_loot - seen_keys)
    for ident in stale:
        print(f"[divergent-creatures] baseline entry no longer diverges, drop it "
              f"from tests/known_loot_divergence.json — {ident}")

    if loot_new:
        print(f"[divergent-creatures] FAIL: {len(loot_new)} NEW loot divergence(s) — a "
              "placement disagrees with its blueprint about whether an item is "
              "droppable, so the loot works exactly once per reboot and reverts "
              "on respawn:", file=sys.stderr)
        for entry in loot_new:
            print(f"  - {entry}", file=sys.stderr)
        print("\nFix: make the placement and the blueprint agree (see "
              "CLAUDE-loot-divergence-audit.md), or — if this is deliberate and "
              "you accept it reverting on respawn — add it to "
              "tests/known_loot_divergence.json via "
              "`bin/audit-loot-divergence.py --baseline`.", file=sys.stderr)
        return 1

    if failures:
        print(f"[divergent-creatures] FAIL: {len(failures)} blueprint(s) have placements "
              f"that will revert to the blueprint on respawn:", file=sys.stderr)
        for base, kind, detail in failures:
            print(f"  - {base:<20} [{kind}] {detail}", file=sys.stderr)
        print("\nFix: run `python3 bin/split-divergent-creatures.py` to give each diverging "
              "placement its own blueprint (see se_respawn_inc.nss).", file=sys.stderr)
        return 1

    total = sum(len(v) for v in placements.values())
    known_note = (f", {len(loot_known)} known loot divergence(s) reported"
                  if loot_known else "")
    print(f"[divergent-creatures] OK: all {total} static creature placements respawn faithfully "
          f"({len(placements)} blueprints{known_note}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
